Document: acccheck
Title: Debian acccheck Manual
Author: <insert document author here>
Abstract: This manual describes what acccheck is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/acccheck/acccheck.sgml.gz

Format: postscript
Files: /usr/share/doc/acccheck/acccheck.ps.gz

Format: text
Files: /usr/share/doc/acccheck/acccheck.text.gz

Format: HTML
Index: /usr/share/doc/acccheck/html/index.html
Files: /usr/share/doc/acccheck/html/*.html
